name: 'Copy file'
description: 'Copy files'
inputs:
  flags:
    description: 'Flags to use on the cp command.'
    required: false
    default: ''
  source:
    description: 'Source file'
    required: true
  target:
    description: 'Target file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{inputs.flags}}
    - ${{inputs.source}}
    - ${{inputs.target}}