name: list-test
on:
  push:
jobs:
  list-files:
    name: list-files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      path: terraform/clusters/dev
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "{matrix}={$(ls ${{ env.path }} | jq -R -s -c 'split("\n")[:-1]')} >> $GITHUB_OUTPUT"
