name: list-test
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
jobs:
  get-radix_environment:
    name: get-radix_environment
    runs-on: ubuntu-latest
    outputs:
      radix_environment: ${{ steps.radix_environment.outputs.radix_environment }}
    steps:
      - id: radix_environment
        # env:
        #   GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          x="$(echo '${{ toJson(github.event.pull_request.labels.*.name) }}' | jq -c)"
          if [[ "$(echo "$x" | jq -e '. | any(. == "dev")')" == true ]]; then
            echo "radix_environment=dev" >> $GITHUB_OUTPUT
          fi
  list-files:
    needs: get-radix_environment
    name: list-files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.list }}
    env:
      path: terraform/clusters/${{ needs.get-radix_environment.outputs.radix_environment }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "list=$(ls ${{ env.path }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  # terraform:
  #   needs: list-files
  #   name: Terraform
  #   uses: ./.github/workflows/terraformtest.yml
  #   strategy:
  #     matrix:
  #       filename: ${{ fromJson(needs.list-files.outputs.matrix) }}
  #   with:
  #     cluster_name: ${{ matrix.filename }}
  #     environment: operations
  #     radix_environment: ${{ needs.get-radix_environment.outputs.radix_environment }}
  #     terraform_version: ~1.3.0
  #     working_directory: terraform/clusters/${{ needs.get-radix_environment.outputs.radix_environment }}/${{ matrix.filename }}
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
