name: list-test
on:
  push:
jobs:
  list-files:
    name: list-files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      path: terraform/clusters
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls ${{ env.path }}l | jq -R -s -c 'split("\n")[:-1]')"
