name: list-test
on:
  push:
  pull_request_target:
jobs:
  list-files:
    name: list-files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      path: terraform/clusters/dev
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "{matrix}={$(ls ${{ env.path }} | jq -R -s -c 'split("\n")[:-1]')} >> $GITHUB_OUTPUT"
  check:
    needs: list-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: ${{ fromJson(needs.list-files.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "{test}={${{ matrix.filename }}} >> $GITHUB_OUTPUT"
  terraform:
    needs: list-files
    name: Terraform
    uses: ./.github/workflows/terraform.yml
    with:
      cluster_name: ${{ matrix.filename }}
      environment: operations
      radix_environment: dev
      terraform_version: ~1.3.0
      working_directory: terraform/clusters/dev/${{ inputs.destination }}
      filenames: ${{ needs.list-files.outputs.matrix }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
