name: copy files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file
        uses: sondresjolyst/github-action-copy@master
        with:
          source: "tests/original/foo.txt"
          target: "foo-copy.txt"
