name: copy files
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      target:
        description: "Target"
        required: true
        type: string
      destination:
        description: "Destination"
        required: true
        type: string
        options:
          - "test"
jobs:
  copy:
    runs-on: ubuntu-latest
    env:
      USER_NAME: Automatic
      USER_EMAIL: radix@statoilsrm.onmicrosoft.com
      COMMIT_MESSAGE: copy file
      COMMIT_AUTHOR: bot
    steps:
      - uses: actions/checkout@v3
      - name: copy file
        run: ARGS="" TARGET="${{ inputs.target }}" DEST="${{ inputs.destination }}" .github/workflows/scripts/copy.sh

      - name: Git push
        run: |
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.USER_EMAIL }}"
          git add .
          git commit -a -m "${{ env.COMMIT_MESSAGE }}"
          git push