name: copy files
on: [push]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file
        run: ARGS="" TARGET="./tests/original/foo.txt" DEST="./tests/foo-copy.txt" .github/workflows/scripts/copy.sh
