name: Migrate cluster
on:
  # pull_request:
  # pull_request_target:
  workflow_dispatch:
    inputs:
      environment:
        description: "Cluster environment"
        required: true
        type: choice
        options:
          - "dev"
          - "playground"
          - "prod"
          - "c2"
      target:
        description: "Target"
        required: true
        type: string
        default: weekly-01
      destination:
        description: "Destination"
        required: true
        type: string
        default: weekly-02
      deployCluster:
        description: Whether or not to deploy cluster
        required: false
        type: boolean
        default: false
jobs:
  copy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    env:
      USER_NAME: Automatic
      USER_EMAIL: radix@statoilsrm.onmicrosoft.com
      COMMIT_MESSAGE: copy file
      COMMIT_AUTHOR: radix
    outputs:
      pull_request_sha: ${{ steps.cpr.outputs.pull-request-head-sha }}
    steps:
      - uses: actions/checkout@v3
      - name: copy file
        run: ARGS="-r" TARGET="./terraform/clusters/${{ inputs.environment }}/${{ inputs.target }}" DESTINATION="./terraform/clusters/${{ inputs.environment }}/${{ inputs.destination }}" .github/workflows/scripts/copy.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ github.token }}
          commit-message: New cluster
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: new-cluster
          delete-branch: true
          title: '[migrate] New Cluster'
          assignees: sondresjolyst
          reviewers: sondresjolyst
          labels: |
            migrate
            deploy
  deployCluster:
    if: contains(github.event.pull_request.labels.*.name, 'deploy') && contains(github.event.pull_request.labels.*.name, 'migrate') && github.event_name == 'pull_request'
    name: Deploy Cluster
    needs: copy
    uses: ./.github/workflows/terraform.yml
    with:
      cluster_name: ${{ inputs.destination }}
      branch: ${{ needs.copy.outputs.pull_request_sha }}
      environment: operations
      radix_environment: dev
      terraform_version: ~1.3.0
      working_directory: terraform/clusters/${{ inputs.environment }}/${{ inputs.destination }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}