name: Migrate cluster
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Cluster environment"
        required: true
        type: choice
        options:
          - "dev"
          - "playground"
          - "prod"
          - "c2"
      target:
        description: "Target"
        required: true
        type: string
        default: weekly-01
      destination:
        description: "Destination"
        required: true
        type: string
        default: weekly-02
      deployCluster:
        description: Whether or not to deploy cluster
        required: false
        type: boolean
        default: false
jobs:
  migrate:
    runs-on: ubuntu-latest
    # env:
      # USER_NAME: Automatic
      # USER_EMAIL: radix@statoilsrm.onmicrosoft.com
      # COMMIT_MESSAGE: Copy cluster
      # COMMIT_AUTHOR: radix
    steps:
      - uses: actions/checkout@v3
      - name: Copy cluster
        run: ARGS="-r" TARGET="./terraform/clusters/${{ inputs.environment }}/${{ inputs.target }}" DESTINATION="./terraform/clusters/${{ inputs.environment }}/${{ inputs.destination }}" .github/workflows/scripts/copy.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ github.token }}
          commit-message: New cluster
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: new-cluster
          delete-branch: true
          title: '[migrate] Target: ${{ inputs.target }}, Destination: ${{ inputs.destination }}'
          assignees: equinor/omnia-radix
          reviewers: equinor/omnia-radix
          labels: |
            migrate
            ${{ inputs.environment }}