name: List files
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment
        uses: peter-evans/create-or-update-comment@v2
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            test
            ```
          token: ${{ github.token }}