name: Test
on:
  workflow_run:
    workflows:
      - Migrate cluster
    types: [completed]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy cluster
        run: echo "test"

      - name: Create Pull Request
        id: cpr
        uses: actions/checkout@v3
        with:
          repository: "new-cluster"
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
      - run: |
          touch b
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
